site_name: My Docs
site_url: https://example.com/
nav:
    - Home: 'index.md'
    - Programming:
        - 'HTML docs': 'html.md'
        - 'CSS docs': 'css.md'
        - 'Java Script docs': 'js.md'
        - 'Python docs': 'python.md'
        - 'Django docs': 'django.md'
        - 'Other frameworks docs': 'other_frameworks.md'
    - About:
        - 'About': 'about.md'
        - 'License': 'license.md'
        - 'Release Notes': 'release-notes.md'
theme:
    name: mkdocs
    nav_style: dark